// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GameusQuestSystem","status":true,"description":"v1.0 - A simplistic quest system with various customization options.","parameters":{"Auto Rewards":"true","---------------":"","Words":"","Hidden Reward Text":"??????","No Quests Text":"No Quests","All Word":"All","Completed Word":"Completed","Failed Word":"Failed","In-Progress Word":"In-Progress","Steps Word":"Steps","Rewards Word":"Rewards","Display Options":"","Reverse Layout":"false","Filter Position":"Top","Use Categories":"true","Show Empty Categories":"0","Show Quest Count":"true","Bullet Character":"-","Max Steps":"3","Image Options":"","Use Icons":"true","Completed Image":"","Completed Image Opacity":"128","Failed Image":"","Failed Image Opacity":"128"}}
];
